services:
  app:
    image: node:lts
    container_name: app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command:
      [
        "sh",
        "-c",
        #  "npm cache clean --force && npm cache verify && npm install --loglevel verbose && npm run build && npm run generate && npm run preview"
        "npm cache clean --force && npm cache verify && npm install --loglevel verbose && npm run dev"
      ]
    environment:
      - NODE_ENV='development'
      - VITE_PORT=3000
      - VITE_BASE_URL='/'
      - VITE_API_URL=https://jsonplaceholder.typicode.com
      - VITE_TOKEN_LABEL='seu-token'
